name: GitHub Actions Example

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  base:
    name: Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Local Action
        id: base-action
        uses: ./
        with:
          file-size-threshold: "3M"
